[package]
name = "flux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libflux"
edition = "2021"
path = "src/lib/mod.rs"

[[bin]]
name = "flux-cli"
edition = "2021"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.56"
byteorder = "1.4.3"
